/* Encrypts the private DM folder into data/dm-payload.js.
   Usage:   npm run build
   The DM folder defaults to ../DnD-Wiki-DM (next to this project). Use --dm <path> to change it.
   The password is asked for (typed twice). Set the DMPW environment variable to skip the prompt. */
const fs = require('fs'), path = require('path'), crypto = require('crypto'), readline = require('readline');

const root = path.resolve(__dirname, '..');
const i = process.argv.indexOf('--dm');
const dmDir = path.resolve(i > 0 ? process.argv[i + 1] : path.join(root, '..', 'DnD-Wiki-DM'));

function ask(question) {
  return new Promise(function (resolve) {
    const rl = readline.createInterface({input: process.stdin, output: process.stdout, terminal: true});
    rl._writeToOutput = function (s) { if (s.indexOf(question) === 0 || /[\r\n]/.test(s)) rl.output.write(s); };
    rl.question(question, function (answer) { rl.close(); resolve(answer); });
  });
}

async function getPassword() {
  if (process.env.DMPW) return process.env.DMPW;
  const a = await ask('DM password: ');
  const b = await ask('Type it again: ');
  if (a !== b) { console.error('The two passwords do not match. Nothing was changed.'); process.exit(1); }
  return a;
}

(async function () {
  for (const f of ['extras.js', 'entries.js']) {
    if (!fs.existsSync(path.join(dmDir, f))) {
      console.error('Cannot find ' + path.join(dmDir, f) + '\nKeep the DM folder next to this project, or pass --dm <path>.');
      process.exit(1);
    }
  }
  const pw = (await getPassword()).trim();
  if (pw.length < 12) { console.error('Use at least 12 characters. A few unrelated words works well.'); process.exit(1); }

  const data = {extra: require(path.join(dmDir, 'extras.js')), entries: require(path.join(dmDir, 'entries.js'))};
  const plain = JSON.stringify(data);

  const iter = 600000, salt = crypto.randomBytes(16), iv = crypto.randomBytes(12);
  const key = crypto.pbkdf2Sync(pw, salt, iter, 32, 'sha256');
  const c = crypto.createCipheriv('aes-256-gcm', key, iv);
  const ct = Buffer.concat([c.update(plain, 'utf8'), c.final()]);
  const payload = {iter: iter, salt: salt.toString('base64'), iv: iv.toString('base64'), ct: Buffer.concat([ct, c.getAuthTag()]).toString('base64')};

  // Prove it opens again with the same password before writing anything.
  const d = crypto.createDecipheriv('aes-256-gcm', crypto.pbkdf2Sync(pw, salt, iter, 32, 'sha256'), iv);
  const raw = Buffer.from(payload.ct, 'base64');
  d.setAuthTag(raw.subarray(raw.length - 16));
  const back = Buffer.concat([d.update(raw.subarray(0, raw.length - 16)), d.final()]).toString('utf8');
  if (back !== plain) { console.error('Self-check failed. Nothing was changed.'); process.exit(1); }

  fs.writeFileSync(path.join(root, 'data', 'dm-payload.js'),
    '/* GENERATED by npm run build. Encrypted DM notes. Do not edit by hand, not even a line break. */\n' +
    'var PAYLOAD = ' + JSON.stringify(payload) + ';\n');
  console.log('Wrote data/dm-payload.js (' + data.entries.length + ' DM entries, ' + Object.keys(data.extra).length + ' extras). Commit and push it.');
})();
